/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginPage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krish
 */
public class Admin_ApproveRetailerOrders extends javax.swing.JFrame {

    /**
     * Creates new form Admin_ApproveRetailerOrders
     */
    public Admin_ApproveRetailerOrders() {
        /*call methods on the intitation of this page to populate the jtables and 
        set the various text fields to not be visible for comfort of the user.
        The text fields are used to input information while calling the update method.
        */
        initComponents();
        populateJtable();
        OrderID_TF.setVisible(false);
        Date_TF.setVisible(false);
        Quantity_TF.setVisible(false);
        jTextField_Email.setVisible(false);
        Brand_TF.setVisible(false);
        TF_RE.setVisible(false);//retailer email
    }
    
     public void populateJtable()
    {
        /*
        this method essentially gets the list of orders that have their 
        status as pendning approval, which are then arranged in the
        jtable using a for loop
        */
    RetailerOrder_DB Order = new RetailerOrder_DB();
        ArrayList<RetailerOrder_DB> OrderList = Order.OrderList("Order Pending Approval");
        
        String[] colNames = {"Order ID", "Salesmen Email","Date","Quantity","Brand","Product Details","Retailer Email","Order Status"};
        Object[][] rows = new Object[OrderList.size()][8];

        
        for(int i = 0; i < OrderList.size(); i++){
          
            rows[i][0] = OrderList.get(i).getID();
            rows[i][1] = OrderList.get(i).getSalesmenEmail();
            rows[i][2] = OrderList.get(i).getDateOfSale();
            rows[i][3] = OrderList.get(i).getQuantity();
            rows[i][4] = OrderList.get(i).getBrand();
            rows[i][5] = OrderList.get(i).getProductDetails();
            rows[i][6] = OrderList.get(i).getRetailerEmail();
            rows[i][7] = OrderList.get(i).getOrderStatus();
          
        }
        
        DefaultTableModel mmodel = new DefaultTableModel(rows, colNames);
        jTable_Approval.setModel(mmodel);
        jTable_Approval.setRowHeight(45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Approval = new javax.swing.JTable();
        jButton_Update = new javax.swing.JButton();
        TF_SalesmenEmail = new javax.swing.JTextField();
        TF_OrderStatus = new javax.swing.JTextField();
        OrderID_TF = new javax.swing.JTextField();
        Date_TF = new javax.swing.JTextField();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_LastName = new javax.swing.JLabel();
        Brand_TF = new javax.swing.JTextField();
        Quantity_TF = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        TF_RE = new javax.swing.JTextField();
        Redirect_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1026, 553));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(956, 483));

        jTable_Approval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Salesmen Email", "Date", "Quantity", "Brand", "Product Details", "Retailer Email", "Order Status"
            }
        ));
        jTable_Approval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ApprovalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Approval);

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        TF_SalesmenEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_SalesmenEmailActionPerformed(evt);
            }
        });

        OrderID_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderID_TFActionPerformed(evt);
            }
        });

        Date_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_FirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_FirstName.setText("Salesmen:");

        jLabel_LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LastName.setText("Order Status:");

        Brand_TF.setText("jTextField1");

        Quantity_TF.setText("jTextField1");

        jTextField_Email.setText("jTextField1");

        TF_RE.setText("jTextField1");

        Redirect_Label.setText("BACK TO DASHOBARD>>");
        Redirect_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Redirect_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OrderID_TF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TF_OrderStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TF_SalesmenEmail)
                                    .addComponent(Date_TF)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Quantity_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Brand_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel_FirstName)
                                        .addGap(0, 101, Short.MAX_VALUE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(TF_RE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Redirect_Label)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_SalesmenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_LastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_OrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(OrderID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(Date_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Quantity_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(Brand_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(TF_RE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Redirect_Label)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_ApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ApprovalMouseClicked
        /*
        This tranfers the values of the selected row into the 
        corresponding text fields on the right. Allowing the user
        to edit and update information
        */
        Integer rowIndex = jTable_Approval.getSelectedRow();
        OrderID_TF.setText(jTable_Approval.getValueAt(rowIndex, 0).toString());
        TF_SalesmenEmail.setText(jTable_Approval.getValueAt(rowIndex, 1).toString());
        Date_TF.setText(jTable_Approval.getValueAt(rowIndex, 2).toString());
        Quantity_TF.setText(jTable_Approval.getValueAt(rowIndex, 3).toString());
        Brand_TF.setText(jTable_Approval.getValueAt(rowIndex, 4).toString());
        jTextField_Email.setText(jTable_Approval.getValueAt(rowIndex, 5).toString());
        TF_RE.setText(jTable_Approval.getValueAt(rowIndex, 6).toString());
        TF_OrderStatus.setText(jTable_Approval.getValueAt(rowIndex, 7).toString());
        


    }//GEN-LAST:event_jTable_ApprovalMouseClicked

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
    
        /*
        This section of the code, is used to program the update button
        First the values from the text fields are fetched
        and using the update query from MYSQL the corresponding
        values are update in the database. This is kept in a try catch loop 
        to avoid any exceptions.
        */
        
                String SalesmenEmail = TF_SalesmenEmail.getText();
                String OrderStatus = TF_OrderStatus.getText();
                int ID = Integer.parseInt(OrderID_TF.getText());
                String DateOfSales = Date_TF.getText();
                String ProductDetails = jTextField_Email.getText();
                String Brand = Brand_TF.getText();
                int Quantity = Integer.parseInt(Quantity_TF.getText());
                String RetailerEmail = TF_RE.getText();
                
                

                Connection con = My_CNX.getConnection();
                PreparedStatement ps;
                try {
                  
                    ps = con.prepareStatement("UPDATE `retailerorder` SET `SalesmenEmail`=?,"
                            + "`DateOfSale`=?,`Quantity`=?,`Brand`=?,`ProductDetails`=?,`RetailerEmail`=?,"
                            + "`OrderStatus`=? WHERE `ID` = ?");
                    ps.setString(1, SalesmenEmail);
                    ps.setString(2, DateOfSales);
                    ps.setInt(3, Quantity);
                    ps.setString(4, Brand);
                    ps.setString(5, ProductDetails);
                    ps.setString(6, RetailerEmail);
                    ps.setString(7, OrderStatus);
                    ps.setInt(8, ID);

            if(ps.executeUpdate() != 0){
                JOptionPane.showMessageDialog(null, "Order Status Updated");               
                }
                else{
                    JOptionPane.showMessageDialog(null, "Something Wrong, Try Agin!");                   
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(C_Users.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                populateJtable(); //populate the jtable with the updated values
               
            
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void TF_SalesmenEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_SalesmenEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_SalesmenEmailActionPerformed

    private void OrderID_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderID_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderID_TFActionPerformed

    private void Redirect_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Redirect_LabelMouseClicked
        // TODO add your handling code here:
        this.dispose(); //redirects the user tot he previous page
    }//GEN-LAST:event_Redirect_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ApproveRetailerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ApproveRetailerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ApproveRetailerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ApproveRetailerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_ApproveRetailerOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Brand_TF;
    private javax.swing.JTextField Date_TF;
    private javax.swing.JTextField OrderID_TF;
    private javax.swing.JTextField Quantity_TF;
    private javax.swing.JLabel Redirect_Label;
    private javax.swing.JTextField TF_OrderStatus;
    private javax.swing.JTextField TF_RE;
    private javax.swing.JTextField TF_SalesmenEmail;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_LastName;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Approval;
    private javax.swing.JTextField jTextField_Email;
    // End of variables declaration//GEN-END:variables
}
