/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginPage;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krish
 */
public class Admin_ViewSalesmenRecords extends javax.swing.JFrame {

    /**
     * Creates new form Admin_ViewRecords
     */
    public Admin_ViewSalesmenRecords() {
        initComponents(); //GUI 
        jTextField_Email.setVisible(true);
        populateJtable(); //Popoulates jTable as soon as the form starts
    }

    
    public void populateJtable()
    {
        //Uses the Salesmen List method created in Salesmen_DB class
        //Loop through the array list and populate jtable (on the basis of sales and target)
    SalesmenSale_DB Salesmen = new SalesmenSale_DB();
        ArrayList<SalesmenSale_DB> AllSalesmenSaleList = Salesmen.AllSalesmenSaleList();
        
        String[] colNames = {"Email","Total Sales", "Sales Target"};
        Object[][] rows = new Object[AllSalesmenSaleList.size()][4];

        
        for(int i = 0; i < AllSalesmenSaleList.size(); i++){
          
            rows[i][0] = AllSalesmenSaleList.get(i).getEmail();
            rows[i][1] = AllSalesmenSaleList.get(i).getTotalSales();
            rows[i][2] = AllSalesmenSaleList.get(i).getSalesTarget();
            
          
        }
        
        DefaultTableModel mmodel = new DefaultTableModel(rows, colNames);
        jTable_Approval.setModel(mmodel);
        jTable_Approval.setRowHeight(45);
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Approval = new javax.swing.JTable();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_LastName = new javax.swing.JLabel();
        jLabel_LastName1 = new javax.swing.JLabel();
        jLabel_Bonus = new javax.swing.JLabel();
        jLabel_FirstName1 = new javax.swing.JLabel();
        jLabel_Employee = new javax.swing.JLabel();
        jButton_ViewTopSalesmen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Print_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1026, 553));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(956, 483));

        jTable_Approval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Total Sales", "Sales Target"
            }
        ));
        jTable_Approval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ApprovalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Approval);

        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });

        jLabel_FirstName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_FirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FirstName.setText("Calculate Bonus:");

        jLabel_LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LastName.setText("Bonus:");

        jLabel_LastName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LastName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LastName1.setText("Email (Choose From Table):");

        jLabel_Bonus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Bonus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_FirstName1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_FirstName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FirstName1.setText("Top Employee:");

        jLabel_Employee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Employee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_ViewTopSalesmen.setText("View Top Salesmen");
        jButton_ViewTopSalesmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewTopSalesmenActionPerformed(evt);
            }
        });

        jLabel1.setText("BACK TO DASHOBARD>>");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Print_Button.setText("Print Results");
        Print_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Email)
                            .addComponent(jLabel_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jLabel_LastName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Bonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_FirstName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(Print_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ViewTopSalesmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButton_ViewTopSalesmen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Print_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_FirstName)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_LastName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_LastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTable_ApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ApprovalMouseClicked
      
        //As a row is selected in the table, the respective bonus for the salesmen is shown
        Integer rowIndex = jTable_Approval.getSelectedRow();
        int TS = Integer.parseInt(jTable_Approval.getValueAt(rowIndex, 2).toString());
        int ST = Integer.parseInt(jTable_Approval.getValueAt(rowIndex, 1).toString());
        int Bonus;
        
        //mathematical calculations for bonus based on sales and target
        Bonus = Math.abs((TS - ST)/10);
        jTextField_Email.setText(jTable_Approval.getValueAt(rowIndex, 0).toString());
        jLabel_Bonus.setText((String.valueOf(Bonus)));
        
    }//GEN-LAST:event_jTable_ApprovalMouseClicked

    private void jButton_ViewTopSalesmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewTopSalesmenActionPerformed
        // TODO add your handling code here:
       jLabel_Employee.setText(Topsalesmen()) ;
    }
    public String Topsalesmen(){
       String salesmen = null;
        Connection con = My_CNX.getConnection(); // connection is called
        PreparedStatement ps;
        ResultSet rs;
        
        /*
        To display the name of the salesmen instead of their email, 
        the email is used as a parameter int he SQL query and the corresponding name
        is displayed in the label
        */
        try {
            ps = con.prepareStatement("SELECT * FROM `users` WHERE `Email` = ?"); //query
            String Ema = String.valueOf(jTable_Approval.getValueAt(0,0)); //getting the email of top salesmen
            ps.setString(1, Ema);
            rs = ps.executeQuery();//executing the query
            if(rs.next()){
                salesmen= rs.getString("FirstName")+ " " + rs.getString("LastName"); //combining the first and last name of salesmen
        }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_ViewSalesmenRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
        return salesmen;
    }//GEN-LAST:event_jButton_ViewTopSalesmenActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose(); //redirect to dashboard
    }//GEN-LAST:event_jLabel1MouseClicked

    private void Print_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_ButtonActionPerformed
        // TODO add your handling code here:
        Print();
    }
    public void Print(){
        try {
            boolean print = jTable_Approval.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Unable To Print !!..");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_Print_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewSalesmenRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewSalesmenRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewSalesmenRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewSalesmenRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_ViewSalesmenRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print_Button;
    private javax.swing.JButton jButton_ViewTopSalesmen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Bonus;
    private javax.swing.JLabel jLabel_Employee;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_FirstName1;
    private javax.swing.JLabel jLabel_LastName;
    private javax.swing.JLabel jLabel_LastName1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Approval;
    private javax.swing.JTextField jTextField_Email;
    // End of variables declaration//GEN-END:variables
}
