/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginPage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author Krish
 */
public class Admin_SalesmenTarget extends javax.swing.JFrame {

    /**
     * Creates new form Admin_SalesmenTarget
     */
    
    /*
    This page contanis the information regarding the salesmen
    It allows the admin to activate their acccounts
    It allows the admin to view progress/sales targets/ sales
    Shows the admin the graphical representation of the different brands sold
    
    */
    public Admin_SalesmenTarget() {
        initComponents(); //GUI of the form
        populateComboBox(); //Populate teh combo box that is used to select the salesmen
        
        jComboBox_Email.setVisible(false);
        Label_Achieved.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify tox1his code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Salesmen_ComboBox = new javax.swing.JComboBox();
        Label_SalesmenName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1_Register = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        TF_ST = new javax.swing.JTextField();
        Label_Target = new javax.swing.JLabel();
        Label_TSales = new javax.swing.JLabel();
        Label_Achieved = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton_UpdateDetails = new javax.swing.JButton();
        Button_Graph = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Email = new javax.swing.JComboBox();
        jButton_Activate_Results = new javax.swing.JButton();
        jLabel_Redirect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1026, 553));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(956, 483));

        Salesmen_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Salesmen from dropdown" }));
        Salesmen_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salesmen_ComboBoxActionPerformed(evt);
            }
        });

        Label_SalesmenName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_SalesmenName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Select Salesmen");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salesmen_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(Label_SalesmenName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salesmen_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_SalesmenName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_1_60x60.png"))); // NOI18N

        jLabel1_Register.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_Register.setText("Initialise and Update Salesmen");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sales Target:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total Sales:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Progress:");

        TF_ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_STActionPerformed(evt);
            }
        });

        jLabel8.setText("Set New:");

        jButton_UpdateDetails.setText(">>");
        jButton_UpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateDetailsActionPerformed(evt);
            }
        });

        Button_Graph.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Graph.setText("VIEW BRAND AND AMOUNT DETAILS");
        Button_Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GraphActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Salesmen Details and Statistics");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Label_Target)))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(Label_TSales)
                                .addGap(118, 118, 118)
                                .addComponent(Label_Achieved))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Button_Graph, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_ST, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_UpdateDetails)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Target)
                    .addComponent(Label_TSales)
                    .addComponent(Label_Achieved))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TF_ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jButton_UpdateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jComboBox_Email.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ma" }));
        jComboBox_Email.setToolTipText("");
        jComboBox_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EmailActionPerformed(evt);
            }
        });

        jButton_Activate_Results.setText("Activate Salesmen Account/ Show Results");
        jButton_Activate_Results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Activate_ResultsActionPerformed(evt);
            }
        });

        jLabel_Redirect.setText("<< BACK TO DASHBOARD");
        jLabel_Redirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RedirectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Activate_Results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_Redirect)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Activate_Results, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jLabel_Redirect)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int Index; //declaring the integer variable Index
    private void Salesmen_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salesmen_ComboBoxActionPerformed
        // TODO add your handling code here:
        String SalesmenName= (String) Salesmen_ComboBox.getSelectedItem(); 
        /*Converts the object to a string and gets the selected salesmen
        by the admin and stores it in a String variable called SalesmenName
        */
        Index = (int) Salesmen_ComboBox.getSelectedIndex(); //gets the selected index of the combo box
        Label_SalesmenName.setText(SalesmenName);
        jLabel7.setText((String) jComboBox_Email.getItemAt(Index)); 
        /*find the corresponding email to that selected item(name) using the index
        the 2 combobox acts like parellel arrays where 2 parellel combobox contanis 
        correponding values
        */
       
        Connection con = My_CNX.getConnection(); // connection is called
        PreparedStatement ps;
        ResultSet rs;
        

        
        try {
            ps = con.prepareStatement("SELECT * FROM `salesmen` WHERE `Email` = ?");
            ps.setString(1, jLabel7.getText());
            rs = ps.executeQuery();
            /*
            Select the data corresponding the email (from the combobox)
            using the MySQL query 
            */
            
            if(rs.next()){
            Label_Target.setText(rs.getString("SalesTarget"));
            Label_TSales.setText(rs.getString("TotalSales"));
            //Set the text of the label as per the data fetched from the database
            
            
            if (rs.getString("Achieved").equals(0)){
                Label_Achieved.setText("NO");
            }
            else Label_Achieved.setText("Yes");
                        
            jProgressBar1.setOrientation(SwingConstants.VERTICAL);
                    
                
            jProgressBar1.setMaximum(rs.getInt("SalesTarget"));
            jProgressBar1.setMinimum(0);
            jProgressBar1.setValue(rs.getInt("TotalSales"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin_SalesmenTarget.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_Salesmen_ComboBoxActionPerformed

    private void jComboBox_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EmailActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox_EmailActionPerformed

    private void jButton_Activate_ResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Activate_ResultsActionPerformed
        // TODO add your handling code here:
      
        String EMA = jLabel7.getText();
          // if(checkEmail(EMA)){
        Connection con = My_CNX.getConnection(); // connection is called
        PreparedStatement ps;
        ResultSet rs;
        
                String query = "SELECT * FROM `salesmen` WHERE `Email` = ?";
        try {
            ps = con.prepareStatement(query);
            ps.setString(1, EMA);
            rs = ps.executeQuery();
            if(rs.next()){
            Label_Target.setText(rs.getString("SalesTarget"));
            Label_TSales.setText(rs.getString("TotalSales"));
            Label_Achieved.setText(rs.getString("Achieved"));
           
            } /*check if the the salesmen's data exists in the salesmen table in the database
            if not transfer it and set the default values, if yes show the corresponding results
            */
            else{
                String registerUserQuery = "INSERT INTO `salesmen`(`Email`) VALUES (?)";
                try {
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1,EMA);
            
            
                    if (ps.executeUpdate() != 0 ){
                        JOptionPane.showMessageDialog(null, "Account Activated");
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Error, Try Again.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(WriteComplaints.class.getName()).log(Level.SEVERE, null, ex);
                    }
            
            
        } 
        }
            catch (SQLException ex) {
            Logger.getLogger(Admin_SalesmenTarget.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    
      
      
                
           
        
        
                                   
        
       
    }//GEN-LAST:event_jButton_Activate_ResultsActionPerformed

    private void TF_STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_STActionPerformed

    private void jButton_UpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateDetailsActionPerformed
        // TODO add your handling code here:
        /*
        Converting integers to stings and strings to integers wherever required
        and assigning the varibales the values
        */
        int SalesTarget = Integer.parseInt(TF_ST.getText());
        int TotalSales = Integer.parseInt(Label_TSales.getText());
        boolean Achieved = Boolean.parseBoolean(Label_Achieved.getText());
        String Email = jLabel7.getText();
        
        Connection con = My_CNX.getConnection(); //connection called
        PreparedStatement ps;
        /*
        Update the salesmen target, and thus fill up the progress bar accordingly
        */
        try {
            ps = con.prepareStatement("UPDATE `salesmen` SET `SalesTarget`=?,`Achieved`=?,`TotalSales`=? WHERE `Email` = ?");
            ps.setInt(1, SalesTarget);
            ps.setBoolean(2, Achieved);
            ps.setInt(3, TotalSales);
            ps.setString(4, Email);
 
            if(ps.executeUpdate() != 0){
                JOptionPane.showMessageDialog(null, "Salesmen Detail Updated");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Error"); 
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(C_Users.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
    }//GEN-LAST:event_jButton_UpdateDetailsActionPerformed

    private void jLabel_RedirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel_RedirectMouseClicked

    private void Button_GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GraphActionPerformed
        // TODO add your handling code here:
        PlotGraph();
    }
    public void PlotGraph(){
        
        Connection connection;
        
        String Email = jLabel7.getText();
        
        int Quantity = 0; //intializing the Quantity Variable
        
        //Creating 2 parellel arrays Brands[] and QuantitySoldPerBrand[]
        String Brands[]= new String[5];
        Brands[0] = "A";
        Brands[1] = "B";
        Brands[2] = "C";
        Brands[3] = "D";
        Brands[4] = "E";
         
        int QuantitySoldPerBrand[] = new int[5];
        QuantitySoldPerBrand[0] = 0;
        QuantitySoldPerBrand[1] = 0;
        QuantitySoldPerBrand[2] = 0;
        QuantitySoldPerBrand[3] = 0;
        QuantitySoldPerBrand[4] = 0;
        /*
        the code below is a nested loop that would iterate through the five brands
        and calculate the quanity sold by the salesmen selected
        */
        
        /* Code for summing the quantity sold and then putting it in the first index 
        of the array quanity sold per brand*/
        for (int i= 0; i<5; i++){
            Salesmen_DB quantity = new Salesmen_DB();
            ArrayList<Salesmen_DB> QuantityList = quantity.QuantityList(Email, Brands[i]);

                for(int y = 0; y < QuantityList.size(); y++){
                    QuantitySoldPerBrand[i] += QuantityList.get(y).getQuantity();
                }
    }
            //Creating new dataset   
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(QuantitySoldPerBrand[0],"Quantity Sold", "A");
        dataset.setValue(QuantitySoldPerBrand[1],"Quantity Sold", "B");
        dataset.setValue(QuantitySoldPerBrand[2],"Quantity Sold", "C");
        dataset.setValue(QuantitySoldPerBrand[3],"Quantity Sold", "D");
        dataset.setValue(QuantitySoldPerBrand[4],"Quantity Sold", "E");
        
        //using the dataset to create the graph using JFreeChart
        JFreeChart chart = ChartFactory.createBarChart("Quanity Sold (Brand wise)", "Brands", "Quantity Sold", dataset);
        CategoryPlot P = chart.getCategoryPlot();
        P.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Graph",chart);
        frame.setVisible(true);
        frame.setSize(450,350);
        
    }
    {
        
         
    }//GEN-LAST:event_Button_GraphActionPerformed

    public void populateComboBox(){
    //populating the 2 combo box
    C_Users users = new C_Users();
        ArrayList<C_Users> SalesmenList = users.SalesmenList();
        
        for (C_Users SalesmenList1 : SalesmenList) {
            //get first name and last name and combine those and display those as items
            Salesmen_ComboBox.addItem(SalesmenList1.getFirstName() + " " + SalesmenList1.getLastName());
            jComboBox_Email.addItem(SalesmenList1.getEmail()); //fill the emails in the other combobox
        }
}
//}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_SalesmenTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_SalesmenTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_SalesmenTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_SalesmenTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_SalesmenTarget().setVisible(true);
            }
        });
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Graph;
    private javax.swing.JLabel Label_Achieved;
    private javax.swing.JLabel Label_SalesmenName;
    private javax.swing.JLabel Label_TSales;
    private javax.swing.JLabel Label_Target;
    private javax.swing.JComboBox Salesmen_ComboBox;
    private javax.swing.JTextField TF_ST;
    private javax.swing.JButton jButton_Activate_Results;
    private javax.swing.JButton jButton_UpdateDetails;
    private javax.swing.JComboBox jComboBox_Email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Register;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Redirect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
