/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginPage;

import java.util.ArrayList;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Krish
 */
public class Admin_ViewRecords extends javax.swing.JFrame {

    /**
     * Creates new form Admin_ViewRecords
     */
    public Admin_ViewRecords() {
        initComponents();
        jTextField_Email.setVisible(false);
        jTextField_Tel.setVisible(false);
        jTextField_Pass.setVisible(false);
        
        populateJtable();//populate the jtable with respective values
    }
    
    
    
    public void populateJtable()
    {
        /*
        Calls the method created in C_Users class and uses it create an array list
        that shows pending users first and the approved users
        Using that, I filled the JTable as shown below
        */
    C_Users users = new C_Users();
        ArrayList<C_Users> userList = users.UsersList();
        
        String[] colNames = {"FirstName","LastName","Email","Password","Telephone","UserType","Photograph","Approval"};
        Object[][] rows = new Object[userList.size()][8];

        
        for(int i = 0; i < userList.size(); i++){
          
            rows[i][0] = userList.get(i).getFirstName();
            rows[i][1] = userList.get(i).getLastName();
            rows[i][2] = userList.get(i).getEmail();
            rows[i][3] = userList.get(i).getPassword();
            rows[i][4] = userList.get(i).getTelephone();
            rows[i][5] = userList.get(i).getUserType();
            rows[i][6] = userList.get(i).getPhotograph();
            rows[i][7] = userList.get(i).getApproval();
          
        }
        
        DefaultTableModel mmodel = new DefaultTableModel(rows, colNames);
        jTable_Approval.setModel(mmodel);
        jTable_Approval.setRowHeight(45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Approval = new javax.swing.JTable();
        jButton_Update = new javax.swing.JButton();
        jTextField_Fname = new javax.swing.JTextField();
        jTextField_Lname = new javax.swing.JTextField();
        jTextField_Utype = new javax.swing.JTextField();
        jTextField_Approval = new javax.swing.JTextField();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_LastName = new javax.swing.JLabel();
        jLabel_UType = new javax.swing.JLabel();
        jLabel_Approval = new javax.swing.JLabel();
        jTextField_Tel = new javax.swing.JTextField();
        jTextField_Pass = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_RedirectToLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1026, 553));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(956, 483));

        jTable_Approval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Email", "Password", "Telephone", "User Type", "Photograph", "Approval"
            }
        ));
        jTable_Approval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ApprovalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Approval);

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jTextField_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FnameActionPerformed(evt);
            }
        });

        jTextField_Utype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UtypeActionPerformed(evt);
            }
        });

        jTextField_Approval.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_FirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_FirstName.setText("First Name:");

        jLabel_LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LastName.setText("Last Name:");

        jLabel_UType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_UType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_UType.setText("User Type:");

        jLabel_Approval.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Approval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Approval.setText("Approval Status:");

        jTextField_Tel.setText("jTextField1");

        jTextField_Pass.setText("jTextField1");

        jTextField_Email.setText("jTextField1");

        jLabel_RedirectToLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_RedirectToLogin.setText("Back to Dashboard>>");
        jLabel_RedirectToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RedirectToLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RedirectToLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RedirectToLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel_RedirectToLogin)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Utype, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Lname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_UType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Fname)
                            .addComponent(jLabel_Approval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Approval)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel_FirstName)))
                                .addGap(0, 18, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_RedirectToLogin))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_LastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_UType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Utype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Approval)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Approval, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextField_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        /*
        The update functionality: uses the method created in C_Users class 
        by getting the information from the invisible text fields and the fields
        edited by the user
        */
        try{
            
            if(verifFields())
            {
                String FirstName = jTextField_Fname.getText();
                String LastName = jTextField_Lname.getText();
                String UserType = jTextField_Utype.getText();
                String Approval = jTextField_Approval.getText();
                String Email = jTextField_Email.getText();
                String Telephone = jTextField_Tel.getText();
                String Password = jTextField_Pass.getText();


                // username`, `password`, `user_type`, `fullname`, `tel`, `email
                C_Users user = new C_Users(FirstName, LastName, Email, Password, Telephone, UserType, null, Approval);
                C_Users.updateUser(user);
                populateJtable();
            }
            
        }
        catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Select a User Before Editing", "No User Selected", 1);
                }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jTextField_UtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UtypeActionPerformed

    private void jTextField_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FnameActionPerformed

    private void jTable_ApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ApprovalMouseClicked
        /*
        Enables the functionality of transfering the values from the table
        to the text fields
        */
        Integer rowIndex = jTable_Approval.getSelectedRow();
        jTextField_Fname.setText(jTable_Approval.getValueAt(rowIndex, 0).toString());
        jTextField_Lname.setText(jTable_Approval.getValueAt(rowIndex, 1).toString());
        jTextField_Email.setText(jTable_Approval.getValueAt(rowIndex, 2).toString());
        jTextField_Pass.setText(jTable_Approval.getValueAt(rowIndex, 3).toString());
        jTextField_Tel.setText(jTable_Approval.getValueAt(rowIndex, 4).toString());
        jTextField_Utype.setText(jTable_Approval.getValueAt(rowIndex, 5).toString());
        jTextField_Approval.setText(jTable_Approval.getValueAt(rowIndex, 7).toString());
        
        
    }//GEN-LAST:event_jTable_ApprovalMouseClicked

    private void jLabel_RedirectToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectToLoginMouseClicked

        this.dispose(); //redirect to dashboard
    }//GEN-LAST:event_jLabel_RedirectToLoginMouseClicked

    private void jLabel_RedirectToLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectToLoginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_RedirectToLoginMouseEntered

    private void jLabel_RedirectToLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectToLoginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_RedirectToLoginMouseExited

     // function to check empty fields
    public boolean verifFields()
    {
        /*
        Verify method that checks for the various validations
        */
        if(jTextField_Fname.getText().equals("") || jTextField_Lname.getText().equals("") || jTextField_Utype.getText().equals("") || jTextField_Approval.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty", "Empty Fields", 0);
            return false;
        }else{
            return true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_ViewRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel_Approval;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_LastName;
    private javax.swing.JLabel jLabel_RedirectToLogin;
    private javax.swing.JLabel jLabel_UType;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Approval;
    private javax.swing.JTextField jTextField_Approval;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Fname;
    private javax.swing.JTextField jTextField_Lname;
    private javax.swing.JTextField jTextField_Pass;
    private javax.swing.JTextField jTextField_Tel;
    private javax.swing.JTextField jTextField_Utype;
    // End of variables declaration//GEN-END:variables
}
