/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginPage;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krish
 */
public class Salesmen_UpdateOrderStatus extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public Salesmen_UpdateOrderStatus() {
        initComponents(); //GUI
        populateJtable(); //POPULATE COMBOBOXES
        populateComboBox();
        OrderID_TF.setVisible(false);
        Date_TF.setVisible(false);
        Quantity_TF.setVisible(false);
        TF_SalesmenEmail.setVisible(false);
        jTextField_Email.setVisible(false);
        Brand_TF.setVisible(false);
        TF_RE.setVisible(false);
    }
    
     public void populateJtable()
    {
        String Status = (String) CB_Sort.getSelectedItem();//convert object to string
        String Email = (String) Salesmen_Combobox.getSelectedItem();
        
//using the methods defined in RetailerOrder_DB to show update order status, inputs used to run query
        RetailerOrder_DB Order = new RetailerOrder_DB();
        ArrayList<RetailerOrder_DB> SalesmenOrderList = Order.SalesmenOrderList(Status, Email);
        
        String[] colNames = {"Order ID", "Salesmen Email","Date","Quantity","Brand",
            "Product Details","Retailer Email","Order Status"};
        Object[][] rows = new Object[SalesmenOrderList.size()][8];
        
        for(int i = 0; i < SalesmenOrderList.size(); i++){
          
            rows[i][0] = SalesmenOrderList.get(i).getID();
            rows[i][1] = SalesmenOrderList.get(i).getSalesmenEmail();
            rows[i][2] = SalesmenOrderList.get(i).getDateOfSale();
            rows[i][3] = SalesmenOrderList.get(i).getQuantity();
            rows[i][4] = SalesmenOrderList.get(i).getBrand();
            rows[i][5] = SalesmenOrderList.get(i).getProductDetails();
            rows[i][6] = SalesmenOrderList.get(i).getRetailerEmail();
            rows[i][7] = SalesmenOrderList.get(i).getOrderStatus();
        }
        DefaultTableModel mmodel = new DefaultTableModel(rows, colNames);
        jTable_Approval.setModel(mmodel);
        jTable_Approval.setRowHeight(45);
    }
     
     public void populatejtable(String Email){
        
//using the methods defined in RetailerOrder_DB to show update order status, inputs used to run query
        RetailerOrder_DB Order = new RetailerOrder_DB();
        ArrayList<RetailerOrder_DB> SalesmenOrderList_Allstatus = Order.SalesmenOrderList_Allstatus(Email);
        
        String[] colNames = {"Order ID", "Salesmen Email","Date","Quantity","Brand",
            "Product Details","Retailer Email","Order Status"};
        Object[][] rows = new Object[SalesmenOrderList_Allstatus.size()][8];
        
        for(int i = 0; i < SalesmenOrderList_Allstatus.size(); i++){
          
            rows[i][0] = SalesmenOrderList_Allstatus.get(i).getID();
            rows[i][1] = SalesmenOrderList_Allstatus.get(i).getSalesmenEmail();
            rows[i][2] = SalesmenOrderList_Allstatus.get(i).getDateOfSale();
            rows[i][3] = SalesmenOrderList_Allstatus.get(i).getQuantity();
            rows[i][4] = SalesmenOrderList_Allstatus.get(i).getBrand();
            rows[i][5] = SalesmenOrderList_Allstatus.get(i).getProductDetails();
            rows[i][6] = SalesmenOrderList_Allstatus.get(i).getRetailerEmail();
            rows[i][7] = SalesmenOrderList_Allstatus.get(i).getOrderStatus();        
        }
        
        DefaultTableModel mmodel = new DefaultTableModel(rows, colNames);
        jTable_Approval.setModel(mmodel);
        jTable_Approval.setRowHeight(45);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Approval = new javax.swing.JTable();
        jButton_Update = new javax.swing.JButton();
        TF_SalesmenEmail = new javax.swing.JTextField();
        TF_OrderStatus = new javax.swing.JTextField();
        OrderID_TF = new javax.swing.JTextField();
        Date_TF = new javax.swing.JTextField();
        jLabel_LastName = new javax.swing.JLabel();
        Brand_TF = new javax.swing.JTextField();
        Quantity_TF = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        CB_Sort = new javax.swing.JComboBox();
        jLabel_LastName1 = new javax.swing.JLabel();
        CB_Update = new javax.swing.JComboBox();
        Salesmen_Combobox = new javax.swing.JComboBox();
        jButton_Both = new javax.swing.JButton();
        TF_RE = new javax.swing.JTextField();
        jLabel_Redirect = new javax.swing.JLabel();
        jButton_EmailOnly = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1026, 553));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(956, 483));

        jTable_Approval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Salesmen Email", "Date", "Quantity", "Brand", "Product Details", "Retailer Email", "Order Status"
            }
        ));
        jTable_Approval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ApprovalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Approval);

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        TF_SalesmenEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_SalesmenEmailActionPerformed(evt);
            }
        });

        OrderID_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderID_TFActionPerformed(evt);
            }
        });

        Date_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LastName.setText("View Order:");

        Brand_TF.setText("jTextField1");

        Quantity_TF.setText("jTextField1");

        jTextField_Email.setText("jTextField1");

        CB_Sort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Order Status", "Approved", "Order Shipped", "Order Reached Location", "Transaction Pending", "Order Complete" }));
        CB_Sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_SortActionPerformed(evt);
            }
        });

        jLabel_LastName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LastName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LastName1.setText("Update Order Status:");

        CB_Update.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Order Shipped", "Order Reached Location", "Transaction Pending", "Order Complete" }));
        CB_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_UpdateActionPerformed(evt);
            }
        });

        Salesmen_Combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Your Email" }));
        Salesmen_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salesmen_ComboboxActionPerformed(evt);
            }
        });

        jButton_Both.setText("Show Using Both");
        jButton_Both.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BothActionPerformed(evt);
            }
        });

        TF_RE.setText("jTextField1");

        jLabel_Redirect.setText("BACK TO DASHBOARD>>");
        jLabel_Redirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RedirectMouseClicked(evt);
            }
        });

        jButton_EmailOnly.setText("Show Using Email");
        jButton_EmailOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmailOnlyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_Redirect)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_RE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(Brand_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton_Both, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_EmailOnly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_LastName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OrderID_TF)
                                    .addComponent(TF_OrderStatus)
                                    .addComponent(jLabel_LastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Date_TF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CB_Sort, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CB_Update, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Salesmen_Combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(Quantity_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TF_SalesmenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel_LastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Salesmen_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_Sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Both)
                            .addComponent(jButton_EmailOnly))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_LastName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_OrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantity_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_SalesmenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Brand_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_RE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Redirect)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_ApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ApprovalMouseClicked
       //transfer values from table in text fields
        Integer rowIndex = jTable_Approval.getSelectedRow();
        OrderID_TF.setText(jTable_Approval.getValueAt(rowIndex, 0).toString());
        TF_SalesmenEmail.setText(jTable_Approval.getValueAt(rowIndex, 1).toString());
        Date_TF.setText(jTable_Approval.getValueAt(rowIndex, 2).toString());
        Quantity_TF.setText(jTable_Approval.getValueAt(rowIndex, 3).toString());
        Brand_TF.setText(jTable_Approval.getValueAt(rowIndex, 4).toString());
        jTextField_Email.setText(jTable_Approval.getValueAt(rowIndex, 5).toString());
        TF_RE.setText(jTable_Approval.getValueAt(rowIndex, 6).toString());
        TF_OrderStatus.setText(jTable_Approval.getValueAt(rowIndex, 7).toString());
        


    }//GEN-LAST:event_jTable_ApprovalMouseClicked

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        try{
            {
                //update
                String SalesmenEmail = TF_SalesmenEmail.getText();
                String OrderStatus = TF_OrderStatus.getText();
                int ID = Integer.parseInt(OrderID_TF.getText());
                String DateOfSales = Date_TF.getText();
                String ProductDetails = jTextField_Email.getText();
                String Brand = Brand_TF.getText();
                int Quantity = Integer.parseInt(Quantity_TF.getText());
                String RetailerEmail = TF_RE.getText();


                // username`, `password`, `user_type`, `fullname`, `tel`, `email
                RetailerOrder_DB Order = new RetailerOrder_DB(ID, SalesmenEmail,
                        DateOfSales, Quantity, Brand, ProductDetails, RetailerEmail, OrderStatus);
                RetailerOrder_DB.UpdateOrderStatus(Order);
                populateJtable();
                
            }

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select an Order Before Editing", "No User Selected", 1);
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void TF_SalesmenEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_SalesmenEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_SalesmenEmailActionPerformed

    private void OrderID_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderID_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderID_TFActionPerformed

    private void CB_SortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_SortActionPerformed
        // TODO add your handling code here:
        
        
    
    }//GEN-LAST:event_CB_SortActionPerformed

    private void CB_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_UpdateActionPerformed
        // TODO add your handling code here:
        TF_OrderStatus.setText((String)CB_Update.getSelectedItem());
    }//GEN-LAST:event_CB_UpdateActionPerformed

    private void Salesmen_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salesmen_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salesmen_ComboboxActionPerformed

    private void jButton_BothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BothActionPerformed
        // TODO add your handling code here:
        populateJtable();
    }//GEN-LAST:event_jButton_BothActionPerformed

    private void jLabel_RedirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel_RedirectMouseClicked

    private void jButton_EmailOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmailOnlyActionPerformed
        // TODO add your handling code here:
        populatejtable((String) Salesmen_Combobox.getSelectedItem());
    }//GEN-LAST:event_jButton_EmailOnlyActionPerformed
 
    public void populateComboBox(){
    C_Users users = new C_Users();
        ArrayList<C_Users> SalesmenList = users.SalesmenList();
        
        for (C_Users SalesmenList1 : SalesmenList) {
            //Salesmen_Combobox.addItem(SalesmenList1.getFirstName() + " " + SalesmenList1.getLastName());
            Salesmen_Combobox.addItem(SalesmenList1.getEmail());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salesmen_UpdateOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salesmen_UpdateOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salesmen_UpdateOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salesmen_UpdateOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salesmen_UpdateOrderStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Brand_TF;
    private javax.swing.JComboBox CB_Sort;
    private javax.swing.JComboBox CB_Update;
    private javax.swing.JTextField Date_TF;
    private javax.swing.JTextField OrderID_TF;
    private javax.swing.JTextField Quantity_TF;
    private javax.swing.JComboBox Salesmen_Combobox;
    private javax.swing.JTextField TF_OrderStatus;
    private javax.swing.JTextField TF_RE;
    private javax.swing.JTextField TF_SalesmenEmail;
    private javax.swing.JButton jButton_Both;
    private javax.swing.JButton jButton_EmailOnly;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel_LastName;
    private javax.swing.JLabel jLabel_LastName1;
    private javax.swing.JLabel jLabel_Redirect;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Approval;
    private javax.swing.JTextField jTextField_Email;
    // End of variables declaration//GEN-END:variables
}
