/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginPage;

import javax.swing.ButtonGroup;
import javax.swing.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLEncoder;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Krish
 */
public class SignUpForm extends javax.swing.JFrame {
    
  String Image_Path = null;
    public SignUpForm() {
        initComponents();
    }
    
    
 ButtonGroup bg = new ButtonGroup();
 public void go()
 {
     //create radiobutton group
      bg.add(jRadioButton_Admin);
      bg.add(jRadioButton_Salesmen);
      bg.add(jRadioButton_Retailer);
 }

     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1_Register = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_LastName = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_ConfirmPassword = new javax.swing.JLabel();
        jLabel_Telephone = new javax.swing.JLabel();
        jLabel_UserType = new javax.swing.JLabel();
        jLabel_Photograph = new javax.swing.JLabel();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jPasswordField_ConfirmPassword = new javax.swing.JPasswordField();
        jTextField_FirstName = new javax.swing.JTextField();
        jTextField_LastName = new javax.swing.JTextField();
        jTextField_Telephone = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jRadioButton_Admin = new javax.swing.JRadioButton();
        jRadioButton_Salesmen = new javax.swing.JRadioButton();
        jRadioButton_Retailer = new javax.swing.JRadioButton();
        jCheckBox_ShowPasswordPassword = new javax.swing.JCheckBox();
        jCheckBox_ShowConfirmPassword = new javax.swing.JCheckBox();
        jButton_BrowseImage = new javax.swing.JButton();
        jButton_CreateAccount = new javax.swing.JButton();
        jLabel_RedirectToLogin = new javax.swing.JLabel();
        jLabel_ImagePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1_Register.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_Register.setText("Create Account");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_1_60x60.png"))); // NOI18N

        jLabel_FirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_FirstName.setText("First Name:");

        jLabel_LastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_LastName.setText("Last Name:");

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Email.setText("Email:");

        jLabel_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Password.setText("Password:");

        jLabel_ConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_ConfirmPassword.setText("Confirm Password:");

        jLabel_Telephone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Telephone.setText("Telephone:");

        jLabel_UserType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_UserType.setText("User Type:");

        jLabel_Photograph.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Photograph.setText("Upload Photograph:");

        jPasswordField_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPasswordField_ConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_FirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_LastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_Telephone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_TelephoneKeyTyped(evt);
            }
        });

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        buttonGroup1.add(jRadioButton_Admin);
        jRadioButton_Admin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Admin.setText("Admin");
        jRadioButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Salesmen);
        jRadioButton_Salesmen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Salesmen.setText("Salesmen");

        buttonGroup1.add(jRadioButton_Retailer);
        jRadioButton_Retailer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Retailer.setText("Retailer");
        jRadioButton_Retailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_RetailerActionPerformed(evt);
            }
        });

        jCheckBox_ShowPasswordPassword.setText("Show");
        jCheckBox_ShowPasswordPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowPasswordPasswordActionPerformed(evt);
            }
        });

        jCheckBox_ShowConfirmPassword.setText("Show");
        jCheckBox_ShowConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowConfirmPasswordActionPerformed(evt);
            }
        });

        jButton_BrowseImage.setText("Select Image");
        jButton_BrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseImageActionPerformed(evt);
            }
        });

        jButton_CreateAccount.setBackground(new java.awt.Color(255, 102, 102));
        jButton_CreateAccount.setText("Submit and Create Account");
        jButton_CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateAccountActionPerformed(evt);
            }
        });

        jLabel_RedirectToLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_RedirectToLogin.setText("Back to Login Page>>");
        jLabel_RedirectToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RedirectToLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RedirectToLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RedirectToLoginMouseExited(evt);
            }
        });

        jLabel_ImagePath.setText("Image Path");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_FirstName)
                            .addComponent(jLabel_LastName)
                            .addComponent(jLabel_Telephone)
                            .addComponent(jLabel_UserType))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton_Admin)
                            .addComponent(jRadioButton_Salesmen)
                            .addComponent(jRadioButton_Retailer)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jTextField_LastName)
                            .addComponent(jTextField_Telephone))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Password, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Photograph, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_ConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox_ShowPasswordPassword)
                            .addComponent(jCheckBox_ShowConfirmPassword)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_BrowseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_ImagePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(jPasswordField_Password)
                            .addComponent(jPasswordField_ConfirmPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_RedirectToLogin)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1_Register)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName)
                            .addComponent(jLabel_Email)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_LastName)
                            .addComponent(jLabel_Password)
                            .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_ShowPasswordPassword)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Telephone)
                            .addComponent(jLabel_ConfirmPassword)
                            .addComponent(jPasswordField_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_ShowConfirmPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_UserType)
                            .addComponent(jRadioButton_Admin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_Photograph)
                                .addComponent(jButton_BrowseImage)
                                .addComponent(jLabel_ImagePath))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Salesmen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_Retailer)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_CreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_RedirectToLogin)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_AdminActionPerformed

    private void jCheckBox_ShowConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ShowConfirmPasswordActionPerformed
        //confirm password validations
        if (jCheckBox_ShowConfirmPassword.isSelected())
        {
            jPasswordField_ConfirmPassword.setEchoChar((char)0);
        }
        else
        {
            jPasswordField_ConfirmPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_ShowConfirmPasswordActionPerformed

    private void jCheckBox_ShowPasswordPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ShowPasswordPasswordActionPerformed

        //show password checkbox program
        if (jCheckBox_ShowPasswordPassword.isSelected())
        {
            jPasswordField_Password.setEchoChar((char)0);
        }
        else
        {
            jPasswordField_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_ShowPasswordPasswordActionPerformed

    private void jTextField_TelephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TelephoneKeyTyped
        // TODO add your handling code here:
        //only numbers no letters 
        if(!Character.isDigit(evt.getKeyChar()))
         {
           evt.consume();
         }
    }//GEN-LAST:event_jTextField_TelephoneKeyTyped

    private void jRadioButton_RetailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_RetailerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_RetailerActionPerformed

    private void jButton_BrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseImageActionPerformed
       //Image Chooser
        //get picture by browsing
        String path = null;
        JFileChooser chooser = new JFileChooser();
        
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Image",".jpg",".png",".jpeg");
        chooser.addChoosableFileFilter(extension);
        
        int filestate = chooser.showSaveDialog(null);
        
        if (filestate == JFileChooser.APPROVE_OPTION){
            File selectedImage = chooser.getSelectedFile();
              path = selectedImage.getAbsolutePath();
              jLabel_ImagePath.setText(path);
              
              Image_Path = path;
              
                            
        }
        
        
    }//GEN-LAST:event_jButton_BrowseImageActionPerformed

    private void jButton_CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateAccountActionPerformed
        // TODO add your handling code here:
          
        //assign usertype based on radiobutton
        String fname = jTextField_FirstName.getText();
        String lname = jTextField_LastName.getText();
        String phone = jTextField_Telephone.getText();
        String pass1 = String.valueOf(jPasswordField_ConfirmPassword.getPassword());
        String pass2 = String.valueOf(jPasswordField_Password.getPassword());
        String email = jTextField_Email.getText();
        String userType = "Admin";
        
        if(jRadioButton_Salesmen.isSelected()){
            userType = "Salesmen";
        }
        else if(jRadioButton_Retailer.isSelected()){
            userType = "Retailer";
        }
        else if(jRadioButton_Admin.isSelected()){
        userType = "Admin";
        }
        
        if(verifyFields())
        {
            if(!checkEmail(email))
            {
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `users`(`FirstName`, `LastName`, `Email`, `Password`, `Telephone`, "
                        + "`UserType`, `Photograph`) VALUES (?,?,?,?,?,?,?)";
                 //register user using insert in sql
                try {
                   
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1,fname);
                    ps.setString(2,lname);
                    ps.setString(3,email);
                    ps.setString(4,pass1);
                    ps.setString(5,phone);
                    ps.setString(6,userType);
                    try {
                        if (Image_Path != null){
                             InputStream image = new FileInputStream(new File(Image_Path));
                        ps.setBlob(7, image);
                        } else{
                            ps.setNull(7, java.sql.Types.NULL);
                        }
                        
                        if (ps.executeUpdate() != 0 ){
                            JOptionPane.showMessageDialog(null, "Account Pending Admin Approval...");
                            
                            try
                                {
                                    String message= "Queen Decors: Account Sent For Approval...";
                                    String number = jTextField_Telephone.getText();
		
                                String apiKey="NAcXvn8mrxHt1uWYzKMjaF5JIPlLByQbDTZO7S9kUi4oswhgd2eb6N2mTgwAYup9ClKfMv4EPdnIBDas";
                                String sendId="FSTSMS";
                                //important step...
                                 message =URLEncoder.encode(message, "UTF-8");
                                String language="english";

                                String route="p";
                                String myUrl="https://www.fast2sms.com/dev/bulk?authorization="+apiKey+"&sender_id="+sendId+
                                        "&message="+message+"&language="+language+"&route="+route+"&numbers="+number;

                                //sending get request using java..
                                URL url=new URL(myUrl);
                                HttpsURLConnection con=(HttpsURLConnection)url.openConnection();

                                con.setRequestMethod("GET");
                                con.setRequestProperty("User-Agent", "Mozilla/5.0");
                                con.setRequestProperty("cache-control", "no-cache");
                                System.out.println("Wait..............");
                                int code=con.getResponseCode();
                                System.out.println("Response code : "+code);
                                StringBuffer response=new StringBuffer();
                                BufferedReader br=new BufferedReader(new InputStreamReader(con.getInputStream()));
                                while(true)
                                {
                                        String line=br.readLine();
                                        if(line==null)
                                        {
                                                break;
                                        }
                                        response.append(line);
                                        JOptionPane.showMessageDialog(null, "message"+line);
                                }
                                System.out.println(response);

                                }catch (Exception e) {
                                        // TODO: handle exception
                                        e.printStackTrace();
                                }
                           
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Error");
                        }
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                        
                
            }
        }
    }//GEN-LAST:event_jButton_CreateAccountActionPerformed

    private void jLabel_RedirectToLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectToLoginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_RedirectToLoginMouseEntered

    private void jLabel_RedirectToLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectToLoginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_RedirectToLoginMouseExited

    private void jLabel_RedirectToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RedirectToLoginMouseClicked
            LoginPage rf = new LoginPage();
            rf.setVisible(true);
            rf.pack();
            rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();

    }//GEN-LAST:event_jLabel_RedirectToLoginMouseClicked
//Function for checking empty fields
    
    public boolean verifyFields()
    {
        String fname = jTextField_FirstName.getText();
        String lname = jTextField_LastName.getText();
        String phone = jTextField_Telephone.getText();
        String pass1 = String.valueOf(jPasswordField_ConfirmPassword.getPassword());
        String pass2 = String.valueOf(jPasswordField_Password.getPassword());
        String email = jTextField_Email.getText();
    
    
    // check empty fields
        if(fname.trim().equals("") || lname.trim().equals("") || phone.trim().equals("")|| 
                pass1.trim().equals("") || pass2.trim().equals("") || email.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
            return false;
        }
        
         // check if the two password are equals or not
        else if(!pass1.equals(pass2))
        {
           JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2); 
           return false;
        }
         // if everything is ok
        else{
            return true;
        }
    }
    
    //Fuction to check if an email already exists or not
    
    public boolean checkEmail(String email)
    {
        PreparedStatement st;
        ResultSet rs;
        boolean email_exist = false;
        
        String query ="SELECT * FROM `users` WHERE `Email` = ?";
        
      try {
           st = My_CNX.getConnection().prepareStatement(query);
           st.setString(1, email);
           rs = st.executeQuery();
           
           if(rs.next())
           {
               email_exist = true;
               JOptionPane.showMessageDialog(null, "Please enter a correct email!", "Email Failed", 2);
           }
        
      } catch (SQLException ex) {
          Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
      }
       
                 return email_exist;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_BrowseImage;
    private javax.swing.JButton jButton_CreateAccount;
    private javax.swing.JCheckBox jCheckBox_ShowConfirmPassword;
    private javax.swing.JCheckBox jCheckBox_ShowPasswordPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Register;
    private javax.swing.JLabel jLabel_ConfirmPassword;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_ImagePath;
    private javax.swing.JLabel jLabel_LastName;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Photograph;
    private javax.swing.JLabel jLabel_RedirectToLogin;
    private javax.swing.JLabel jLabel_Telephone;
    private javax.swing.JLabel jLabel_UserType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_ConfirmPassword;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JRadioButton jRadioButton_Admin;
    private javax.swing.JRadioButton jRadioButton_Retailer;
    private javax.swing.JRadioButton jRadioButton_Salesmen;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_Telephone;
    // End of variables declaration//GEN-END:variables


}
